### ISSUE TITLE
error installing plugin

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-boilerplate-plugin#12]
Fatal error: Uncaught Error: Interface 'B4bprojectsVendor\EightshiftLibs\Plugin\HasActivationInterface' not found in /Applications/MAMP/htdocs/bit4bytes/wp-content/plugins/b4bprojects/src/Activate.php:20
Stack trace:
#0 phar:///Applications/MAMP/Library/bin/wp/vendor/composer/ClassLoader.php(444): include()
#1 phar:///Applications/MAMP/Library/bin/wp/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Applications/M...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('B4bprojects\\Act...')
#3 /Applications/MAMP/htdocs/bit4bytes/wp-content/plugins/b4bprojects/src/PluginFactory.php(24): spl_autoload_call('B4bprojects\\Act...')
#4 /Applications/MAMP/htdocs/bit4bytes/wp-content/plugins/b4bprojects/b4bprojects.php(46): B4bprojects\PluginFactory::activate()
#5 /Applications/MAMP/htdocs/bit4bytes/wp-includes/class-wp-hook.php(303): B4bprojects\{closure}(NULL)
#6 /Applications/MAMP/htdocs/bit4bytes/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /Applications/MAMP/htdoc in /Applications/MAMP/htdocs/bit4bytes/wp-content/plugins/b4bprojects/src/Activate.php on line 20

**Comment by marijang** [comment]
also wp boilerplate setup_plugin  not works

**Comment by dingo-d** [comment]
Hi @marijang,

I'm not sure that we did some work on plugin boilerplate lately. We'll need to check this out.

Thanks!

**Comment by marijang** [comment]
in webpack.config js you have 

projectPath: 'wp-content/plugins/b4bprojects-plugin', // Project path relative to project root.

but wizard create....create dir b4bprojects not b4bprojects-plugin

**Comment by marijang** [comment]
npm start also not working

**Comment by psaikali** [comment]
Any news on this? Would love to try this boilerplate but activating the plugin is impossible :/

**Comment by psaikali** [comment]
Renaming all occurences of `use XYZVendor` to `use XYZPluginVendor` did the trick!

**Comment by iruzevic** [comment]
done
