### ISSUE TITLE
[QUESTION] - Published plugin based on Eightshift?

### ISSUE THREAD

**Issue by mrtn97** [infinum/eightshift-boilerplate-plugin#17]
Hi there,

Are there realised WordPress plugins based on Eightshift? It could be of great help for newbies like me.

**Comment by mbmjertan** [comment]
Take a look at [infinum/eightshift-forms](https://github.com/infinum/eightshift-forms). It's not on wp.org plugins afaik, but probably the best Eightshift-based plugin you can find publicly.
